export const CREATE_LANE = 'CREATE_LANE';
export const UPDATE_LANE = 'UPDATE_LANE';
export const DELETE_LANE = 'DELETE_LANE';
export const ATTACH_TO_LANE = 'ATTACH_TO_LANE';
export const DETACH_FROM_LANE = 'DETACH_FROM_LANE';
export const MOVE_FROM_LANE_TO_LANE = 'MOVE_FROM_LANE_TO_LANE';
